### ISSUE TITLE
Add dataset uploading

### ISSUE THREAD

**Issue by nginyc** [nginyc/rafiki#107]
- [x] User to create datasets through upload & by link with Rafiki Client
- [x] User to list available datasets with Rafiki Client
- [x] User to create train jobs with created datasets with Rafiki Client
- [x] User to create datasets through upload & by link on web
- [x] User to list available datasets on web
- [x] User to create train jobs with created datasets on web

**Comment by wild-flame** [comment]
Can add me as an assignee :D
