### ISSUE TITLE
Add A logo for Rafiki

### ISSUE THREAD

**Issue by wild-flame** [nginyc/rafiki#135]

**Comment by wild-flame** [comment]
![Dark](https://user-images.githubusercontent.com/4491950/60785365-40b77d00-a185-11e9-85b3-eea511ce80b6.png)
![Light](https://user-images.githubusercontent.com/4491950/60785366-40b77d00-a185-11e9-905d-466650497c1a.png)

Just a draft logo

**Comment by nudles** [comment]
We have one logo
![image](https://user-images.githubusercontent.com/3797447/60857710-1e356a80-a23e-11e9-9d72-a095d4f44eb1.png)
.. but we are considering renaming the project, e.g., SingaX.

**Comment by wild-flame** [comment]
Noted :D
