### ISSUE TITLE
The web admin cannot read host address from environmental variables

### ISSUE THREAD

**Issue by wild-flame** [nginyc/rafiki#153]
Even after run

`export RAFIKI_ADDR=ncrs.d2.comp.nus.edu.sg`

The web admin is use the default host `localhost` as the base of API endpoint in production environment.

should take a look into the docker image and figure out why.

**Comment by vaanforz** [comment]
Currently, I can only successfully access web admin on NCRS host by hardcoding:

`        window.ADMIN_HOST = 'ncrs.d2.comp.nus.edu.sg'
        window.ADMIN_PORT = 3000`

instead of updating .env.sh.
