### ISSUE TITLE
Dev branch: create_train_job() missing 1 positional argument ‘train_args’

### ISSUE THREAD

**Issue by vaanforz** [nginyc/rafiki#155]
Dev branch: create_train_job() missing 1 positional argument ‘train_args’

Using the dev branch and hosting Rafiki on NCRS, I tried to simulate the UI workflow by uploading a dataset and creating a train job instead of calling methods from the python client directly. 

However, upon clicking 'create job' on the UI, this error shows up:
![image](https://user-images.githubusercontent.com/8429578/61868653-67f3a580-af0c-11e9-818c-b6f6c6560217.png)

This error occurs regardless of the datasets and model files used (tried the default fashion_mnist.zip and VGG16 as well as foodlg dataset and Xception).

The way to circumvent this error is by calling create_train_job() directly from python and manually referencing the dataset_id from the id generated in the web admin UI.

`client.create_train_job(
    app='Foodlg_xception',
    task='IMAGE_CLASSIFICATION',
    train_dataset_id='abcc6220-a348-421f-8260-a4ec95e87a32',
    val_dataset_id='89de9eb3-0c38-4bc4-8a60-207744e86a29',
    budget={ 'MODEL_TRIAL_COUNT': 1, 'GPU_COUNT': 0  }
)`

**Comment by nginyc** [comment]
Hi @vaanforz, thanks for the bug report.

I believe I've encountered this issue and I've incorporated a fix in my latest PR @ #152. Is it okay if you help verify that this error doesn't appear in that `add_colour_images` branch?

**Comment by nginyc** [comment]
@vaanforz when it's verified to be working on `dev`, you can close this issue
