### ISSUE TITLE
Preparing for making a Release to master 

### ISSUE THREAD

**Issue by wild-flame** [nginyc/rafiki#166]
- [x] running all of Rafiki’s tests 
- [x] remember to re-build the Docker images to ensure the latest code changes are reflected (see Testing Latest Code Changes)
- [x] running all of Rafiki’s example models in ./examples/models/
- [x] running all of Rafiki’s example usage scripts in ./examples/scripts/
- [x] running all of Rafiki’s example dataset-preparation scripts in ./examples/datasets/
- [x] visiting Rafiki Web Admin and manually testing it
- [x] building Rafiki’s documentation site and checking if the documentation matches

**Comment by nginyc** [comment]
Already merged to `master`
