### ISSUE TITLE
Setup framework for running tests

### ISSUE THREAD

**Issue by nginyc** [nginyc/rafiki#89]
There are no tests for Rafiki, making it hard to determine whether there were any regressions. 

We would want a single line `test` command and a framework to add/modify tests, which would reliably ensure that our code works as intended when changes are made.

**Comment by nudles** [comment]
I suggest to go top-down manner to save time of doing test for very small functions.
e.g., 
```
def funcA():
    funcB()
    funcC()

def funcB():

def funcC():
```
We do test for funcA().

**Comment by nginyc** [comment]
ok understood. i will mainly add end-to-end tests e.g. full train-inference flow
